name: slowloris
description: Low bandwidth DoS tool. Slowloris rewrite in Dart.
version: 0.2.6
repository: https://github.com/xphc-swissas/slowloris

environment:
  sdk: ^3.10.2

# Add regular dependencies here.
dependencies:
  args: ^2.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

executables:
  slowloris:
